services:
  - type: web
    name: raaga-backend
    runtime: docker
    plan: free
    healthCheckPath: /api/music/test
    envVars:
      - key: PORT
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: MUSIC_API_BASE_URL
        value: https://jiosaavn-api-gato.onrender.com
